### ISSUE TITLE
keep being told the letter I chose was not in the word. Tried every letter.Why?

### ISSUE THREAD

**Issue by ShaleKing** [kying18/hangman#7]
import random
from words import words
import string

def get_valid_word(words):
    word = random.choice(words)
    while '-' in word or ' ' in word:
        word = random.choice(words)

    return word

def hangman():
    word = get_valid_word(words)
    word_letters = set(word)
    alphabet = set(string.ascii_uppercase)
    used_letters = set()

    lives = 1000

    while len(word_letters) > 0 and lives > 0:
        print('You have', lives, 'lives left and you have used these letters: ', ' '.join(used_letters))

        word_list = [letter if letter in used_letters else '-' for letter in word]
        print('Current word: ', ' '.join(word_list))

        user_letter = input('Guess a letter: ').upper()
        if user_letter in alphabet - used_letters:
            used_letters.add(user_letter)
            if user_letter in word_letters:
                word_letters.remove(user_letter)
                print('')

            else:
                lives = lives - 1
                print('That letter is not in the word. Please try again.')

        elif user_letter in used_letters:
            print('You have already used that letter. Please try again.')
        
        else:
            print('Invalid character. Please try again.')

    if lives == 0:
        print('You died, sorry. The word was ', word)
    else:
        print('You have guess the word', word, '!')

while __name__ == '__main__':
    hangman()

**Comment by ar1atsu** [comment]
not entirely sure and u seem to have already resolved this issue but if u see this please confirm, the issue is that you used word_letters.remove(user_letter) while that would take it out of the word which would always cause it to not be in the word.
